- hosts: localhost
  vars:
    profile_name: myprofile    
  tasks:

    - name: check if profile exists
      shell: bash get_profile_id.sh {{ profile_name }}
      register: profile_id_exists

    - name: Check contents for emptiness
      ansible.builtin.debug:
        msg: "{{ profile_id_exists.stdout }}"
      
