# https://docs.ansible.com/ansible/latest/modules/dconf_module.html
#
# To determine what dconf keys and values to use, you can run `dconf watch /`
# in a terminal as you make changes in settings or tweaks.  You can also use
# `dconf read <key>` and `dconf write <key> <value>` to experiment with various
# settings.  The dconf-editor application is also useful for exploring various
# keys along with their descriptions.

- hosts: localhost
  tasks:

          
    #############
    # shortcuts #
    #############

    # There are many built-in shortcut actions that only require setting a
    # binding to enable.

    - name: file browser shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/home"
        value: "['<Super>f']"

    - name: web browser shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/www"
        value: "['<Super>w']"

    # various #
    
    - name: no autorun promt
      dconf:
        key: "/org/gnome/desktop/media-handling/autorun-never"
        value: "true"
