# ansible-playbook test.yml  --ask-become-pass
- hosts: localhost
  tasks:

    - name: install playbook requirements (debian)
      become: true
      package:
        name:
          - python3-psutil
          - dconf-cli
          - git
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install playbook requirements (arch)
      become: true
      package:
        name:
          - python-psutil
          - dconf
          - git
      when: ansible_distribution == 'Archlinux'

    - name: install playbook requirements (Fedora)
      become: true
      package:
        name:
          - python3-psutil
          - dconf
          - git
      when: ansible_distribution == 'Fedora'